/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.example;

import java.util.Arrays;

public class App {
  public static int getNumberOfWaysToCreateSum(int sum, int[] coins) {
    int[] dp = new int[sum + 1];
    Arrays.fill(dp, 0);
    Arrays.sort(coins);
    dp[0] = 1;
    for (int coinItem :
      coins) {
      for (int i = coinItem; i <= sum; i++) {
        if (i >= coinItem) {
          dp[i] += dp[i - coinItem];
        }
      }
    }
    return dp[sum];
  }

  public static void main(String[] args) {
    int sum = 4;
    int[] coins = {1, 2, 3};
    System.out.println(new App().getNumberOfWaysToCreateSum(sum, coins));
    //
  }
}
