/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {
    public static int getNumberOfWaysToCreateSum(int sum, int[] coin){
        return -1;
    }

    public static void main(String[] args) {
        int sum = 4;
        int[] coins = {1, 2, 3};
        System.out.println(new App().getNumberOfWaysToCreateSum(sum, coins));
    }
}
